# Generated by Django 4.2.5 on 2023-09-12 03:40

import app_blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_rename_post_date_post_post_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=app_blog.models.Category.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_blog.category'),
        ),
    ]
