# Generated by Django 4.2.5 on 2023-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click on the title to read more...', max_length=255),
        ),
    ]
